// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddressRow: typeof import('./src/components/address/address-row.vue')['default']
    CartList: typeof import('./src/components/cart/cart-list.vue')['default']
    DictColumn: typeof import('./src/components/dict/dict-column.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    OrderRow: typeof import('./src/components/order/order-row.vue')['default']
    ProductCover: typeof import('./src/components/product/product-cover.vue')['default']
    ProductRow: typeof import('./src/components/product/product-row.vue')['default']
    ProductSkuDialog: typeof import('./src/components/product/product-sku-dialog.vue')['default']
    RegisterPopup: typeof import('./src/components/register-popup/register-popup.vue')['default']
    UserAvatar: typeof import('./src/components/user/user-avatar.vue')['default']
    UserRow: typeof import('./src/components/user/user-row.vue')['default']
    WalterFall: typeof import('./src/components/walter-fall/walter-fall.vue')['default']
  }
}
