// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CartList: typeof import('./src/components/cart/cart-list.vue')['default']
    CouponRow: typeof import('./src/components/coupon/coupon-row.vue')['default']
    DictValue: typeof import('./src/components/dict/dict-value.vue')['default']
    ItemChoose: typeof import('./src/components/item-choose/item-choose.vue')['default']
    LoginPopup: typeof import('./src/components/login-popup/login-popup.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    ProductCover: typeof import('./src/components/product/product-cover.vue')['default']
    ProductRow: typeof import('./src/components/product/product-row.vue')['default']
    ProductSkuDialog: typeof import('./src/components/product/product-sku-dialog.vue')['default']
    UserAvatar: typeof import('./src/components/user/user-avatar.vue')['default']
    UserRow: typeof import('./src/components/user/user-row.vue')['default']
    WalterFall: typeof import('./src/components/walter-fall/walter-fall.vue')['default']
  }
}
