// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    UserAvatar: typeof import('./src/components/user/user-avatar.vue')['default']
    UserRow: typeof import('./src/components/user/user-row.vue')['default']
    WalterFall: typeof import('./src/components/walter-fall/walter-fall.vue')['default']
  }
}
