export const DictConstants = {
  PAY_TYPE: 1004,
  MENU_TYPE: 1002,
  PRODUCT_ORDER_STATUS: 1003,
  GENDER: 1001,
};
export const Dictionaries = {
  PayType: {
    WE_CHAT_PAY: {
      keyId: 0,
      keyName: "微信支付",
      keyEnName: "WE_CHAT_PAY",
      dictId: 1004,
      dictName: "支付类型",
      dictEnName: "PAY_TYPE",
      orderNum: 0,
    },
    ALI_PAY: {
      keyId: 1,
      keyName: "支付宝",
      keyEnName: "ALI_PAY",
      dictId: 1004,
      dictName: "支付方式",
      dictEnName: "PAY_TYPE",
      orderNum: 0,
    },
  },
  MenuType: {
    BUTTON: {
      keyId: 2,
      keyName: "按钮",
      keyEnName: "BUTTON",
      dictId: 1002,
      dictName: "菜单类型",
      dictEnName: "MENU_TYPE",
      orderNum: 2,
    },
    PAGE: {
      keyId: 0,
      keyName: "页面",
      keyEnName: "PAGE",
      dictId: 1002,
      dictName: "菜单类型",
      dictEnName: "MENU_TYPE",
      orderNum: 1,
    },
    DIRECTORY: {
      keyId: 1,
      keyName: "目录",
      keyEnName: "DIRECTORY",
      dictId: 1002,
      dictName: "菜单类型",
      dictEnName: "MENU_TYPE",
      orderNum: 0,
    },
  },
  ProductOrderStatus: {
    CLOSED: {
      keyId: 4,
      keyName: "已关闭",
      keyEnName: "CLOSED",
      dictId: 1003,
      dictName: "商品订单状态",
      dictEnName: "PRODUCT_ORDER_STATUS",
      orderNum: 0,
    },
    REFUNDING: {
      keyId: 5,
      keyName: "退款中",
      keyEnName: "REFUNDING",
      dictId: 1003,
      dictName: "商品订单状态",
      dictEnName: "PRODUCT_ORDER_STATUS",
      orderNum: 0,
    },
    TO_BE_RECEIVED: {
      keyId: 2,
      keyName: "待收货",
      keyEnName: "TO_BE_RECEIVED",
      dictId: 1003,
      dictName: "商品订单状态",
      dictEnName: "PRODUCT_ORDER_STATUS",
      orderNum: 0,
    },
    TO_BE_PAID: {
      keyId: 0,
      keyName: "待付款",
      keyEnName: "TO_BE_PAID",
      dictId: 1003,
      dictName: "商品订单状态",
      dictEnName: "PRODUCT_ORDER_STATUS",
      orderNum: 0,
    },
    TO_BE_EVALUATED: {
      keyId: 3,
      keyName: "待评价",
      keyEnName: "TO_BE_EVALUATED",
      dictId: 1003,
      dictName: "商品订单状态",
      dictEnName: "PRODUCT_ORDER_STATUS",
      orderNum: 0,
    },
    TO_BE_CREATE: {
      keyId: 6,
      keyName: "待创建",
      keyEnName: "TO_BE_CREATE",
      dictId: 1003,
      dictName: "商品订单状态",
      dictEnName: "PRODUCT_ORDER_STATUS",
      orderNum: 0,
    },
    TO_BE_DELIVERED: {
      keyId: 1,
      keyName: "待发货",
      keyEnName: "TO_BE_DELIVERED",
      dictId: 1003,
      dictName: "商品订单状态	",
      dictEnName: "PRODUCT_ORDER_STATUS",
      orderNum: 0,
    },
  },
  Gender: {
    PRIVATE: {
      keyId: 2,
      keyName: "保密",
      keyEnName: "PRIVATE",
      dictId: 1001,
      dictName: "性别",
      dictEnName: "GENDER",
      orderNum: 0,
    },
    MALE: {
      keyId: 0,
      keyName: "男",
      keyEnName: "MALE",
      dictId: 1001,
      dictName: "性别",
      dictEnName: "GENDER",
      orderNum: 0,
    },
    FEMALE: {
      keyId: 1,
      keyName: "女",
      keyEnName: "FEMALE",
      dictId: 1001,
      dictName: "性别",
      dictEnName: "GENDER",
      orderNum: 1,
    },
  },
};
