export { AuthController } from "./AuthController";
export { DictController } from "./DictController";
export { MenuController } from "./MenuController";
export { ProductCategoryController } from "./ProductCategoryController";
export { ProductController } from "./ProductController";
export { ProductSkuController } from "./ProductSkuController";
export { RoleController } from "./RoleController";
export { UserController } from "./UserController";
export { UserWeChatController } from "./UserWeChatController";
